const editorConfig = {
  readonly: false,
  toolbarSticky: false,
  spellcheck: true,
  minHeight: 300,
  placeholder: "Write your description here...",
  buttons: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "|",
    "ul",
    "ol",
    "|",
    "align",
    "outdent",
    "indent",
    "|",
    "link",
    "unlink",
    "|",
    "undo",
    "redo",
    "|",
    "hr",
    "eraser",
    "superscript",
    "subscript",
    "|",
    "font",
    "fontsize",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
  ],
  fontSize: ["12px", "14px", "16px", "18px", "20px", "24px", "32px"],
  fontFamily: [
    "Arial",
    "Verdana",
    "Georgia",
    "Times New Roman",
    "Tahoma",
    "Courier New",
  ],
};

export default editorConfig;
